spring:
  application:
    name: biblioteka
  datasource:
    url: jdbc:h2:mem:biblioteka
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

server:
  port: 8080

biblioteka:
  wypozyczenia:
    limit-na-czytelnika: 3
